resources:
  - url: http://127.0.0.1:5004/weather-chart-cardx.js
    type: module
views:
  - cards:
      - type: custom:weather-chart-cardx
        name: Weather CHart Cardx
        entity: sun.sun
        test_gui: true
